### ISSUE TITLE
Unable add own jobcontrol type mapping

### ISSUE THREAD

**Issue by Koc** [ninethousand/NineThousandJobqueueBundle#3]
I've tryed add my own job control

``` yaml
nine_thousand_jobqueue:
    job:
        class:  NineThousand\Jobqueue\Job\StandardJob
    control:
        class:  NineThousand\Jobqueue\Service\JobqueueControl
    adapter:
        class:  NineThousand\Jobqueue\Vendor\Doctrine\Adapter\Queue\DoctrineQueueAdapter
        options:
            cron_class:                     Cron\CronExpression
            job_entity_class:       NineThousand\Bundle\NineThousandJobqueueBundle\Entity\Job
            job_adapter_class:      NineThousand\Bundle\NineThousandJobqueueBundle\Vendor\Doctrine\Adapter\Job\Symfony2DoctrineJobAdapter
            history_entity_class:   NineThousand\Bundle\NineThousandJobqueueBundle\Entity\History
            history_adapter_class:  NineThousand\Jobqueue\Vendor\Doctrine\Adapter\History\DoctrineHistoryAdapter
            log_adapter_class:      NineThousand\Jobqueue\Vendor\Doctrine\Adapter\Log\MonologAdapter
            jobcontrol:
                type_mapping:
                    SymfonyConsoleJobControl:   NineThousand\Jobqueue\Vendor\Symfony2\Adapter\Job\Control\Symfony2ConsoleJobControl
                    OloloConsoleJobControl: Ololo\Bundle\ProjectBundle\JobQueue\ConsoleJobControl
```

got exception

```
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]

  Unrecognized options "OloloConsoleJobControl" under "nine_thousand_jobqueu
e.adapter.options.jobcontrol.type_mapping"
```
